// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bislbdztrcwwopqqnlkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpc2xiZHp0cmN3d29wcXFubGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODk1MjgsImV4cCI6MjA3NDU2NTUyOH0.jcaDkOnh4GGqj75quViACEyHXR7jHVtFblOSKhZIPqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});